### ISSUE TITLE
Incorrect description for GameClockUpdatedSeconds

### ISSUE THREAD

**Issue by johanalkstal** [pharuxtan/sos-emulator#1]
I think there might be a copy/paste error in the payload for https://github.com/pharuxtan/sos-emulator/blob/322820218773c0ca1ae4a5a28a5d634b04c98a46/src/Components/Payloads/GameClockUpdatedSeconds.svelte#L13

which is the same description as
https://github.com/pharuxtan/sos-emulator/blob/322820218773c0ca1ae4a5a28a5d634b04c98a46/src/Components/Payloads/GameRoundStartedGo.svelte#L13

Perhaps a better description could be "This payload is sent when the seconds of the clock are updated"?

**Comment by pharuxtan** [comment]
Yup, thanks for notice that 😄
I'll change that now, if you notice any other typo feel free to tell me
