### ISSUE TITLE
Boost changes are not reflected in sending data

### ISSUE THREAD

**Issue by tenmihi** [pharuxtan/sos-emulator#2]
<img width="349" alt="スクリーンショット 2022-06-23 16 58 24" src="https://user-images.githubusercontent.com/15909788/175247378-aeb4d0d9-53cd-47bb-9086-17091770ebe1.png">

## Steps to reproduce

In the game:update_state section, add a player and change the boost value from 33 to 100.

## What is expected?

Boost changes are not reflected in sending data.

## What is actually happening?

inputBoost() may not be called depending on the result of filterBoost().

**Comment by pharuxtan** [comment]
Has been fixed in the recent commit, thanks for the issue 😄
